version: '3'
services:
  message-server :
    container_name: message-server
#    build:
#      context: docker-message-server
#      dockerfile: Dockerfile
    image: message-server:latest
    ports:
      - 8081:8081
    hostname: localhost
    networks:
      - spring-cloud-network
  product-server:
    container_name: product-server
#    build:
#      context: docker-product-server
#      dockerfile: Dockerfile
    image: product-server:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
